-- Freeze weekly session-record rollups. Attendance minutes are computed on
-- read from tickets; excuses live in scholar_week_excuses.
-- Team choice for #29 Stage 5: rename + freeze (do not DROP) so SQL still
-- has a snapshot. No app runtime should write these tables.
--
-- SUPERSEDED — NO-OP (2026-09-07): this file was never actually applied to
-- production (confirmed via `supabase migration list --linked`: production
-- has no 20260821010000 entry). Production instead got an equivalent
-- end-state four days later via 20260825003343_reconcile_production_drift.sql
-- — captured from production's real migration history — which drops and
-- recreates front_desk_records/study_session_records as *_legacy rather than
-- renaming them. Running both against a fresh environment in order would
-- break: this file's RENAME would leave `reconcile_production_drift`'s later
-- `DROP TABLE "public"."front_desk_records"` pointing at a table that no
-- longer exists under that name. Left in place (rather than deleted) only to
-- preserve the historical migration-file record; it intentionally does
-- nothing now. See supabase/README.md's Status section for the full story.
