-- Captures a migration that was applied directly to the production project
-- (via the Supabase Dashboard SQL editor or a `db push` from an unmerged
-- branch) without ever landing as a file in this repo. Recovered verbatim
-- from production's supabase_migrations.schema_migrations.statements for
-- version 20260825003343 ("reconcile_production_drift") on 2026-09-07.
--
-- This file is named with that ORIGINAL version/timestamp on purpose: on
-- production, `supabase_migrations.schema_migrations` already has a row for
-- 20260825003343, so `supabase db push`/`migration list --linked` will treat
-- this file as already-applied there and will not re-run it. On any
-- environment that does NOT yet have that version recorded (a fresh
-- `supabase start` local DB, or the "staging" project, which currently has
-- an unrelated, disjoint migration history) applying the full migration set
-- in order will run this for the first time and produce production's actual
-- current schema instead of the stale one supabase/migrations previously
-- implied.
--
-- What it does, in plain terms:
--   * Renames front_desk_records -> front_desk_records_legacy and
--     study_session_records -> study_session_records_legacy (drop + recreate,
--     matching what docs/dev/supabase/public-schema.md already documents as
--     current — the doc was right, the migration history was wrong).
--   * Adds the hypopg, index_advisor, pg_cron, and pgjwt extensions.
--   * Schedules a nightly pg_cron job calling
--     public.full_resync_daily_scholar_activity().
--   * Re-creates on_auth_user_created (auth.users -> public.handle_new_user).
--   * Broadens authenticated_select_activity (daily_scholar_activity) and
--     whaf_select_policy (whaf_form_logs) from "own row only" to "own row OR
--     admin/staff/team_leader/developer".
--   * Adds an ensure_rls event trigger that auto-enables RLS on newly
--     created tables.
--
-- pg_cron requires shared_preload_libraries support from the Postgres
-- instance; if a local `supabase start` stack doesn't have it preloaded,
-- the `create extension "pg_cron"` / `cron.schedule_in_database(...)`
-- statements below will fail there even though they succeed against a
-- hosted Supabase project — comment them out locally if that happens.

set local check_function_bodies = off;

drop policy "authenticated_select_activity" on "public"."daily_scholar_activity";

drop policy "whaf_select_policy" on "public"."whaf_form_logs";

drop table "public"."front_desk_records";

drop table "public"."study_session_records";

create extension if not exists "hypopg" schema "extensions";

create extension if not exists "index_advisor" schema "extensions";

create extension if not exists "pg_cron";

create extension if not exists "pgjwt" schema "extensions";

create table "public"."front_desk_records_legacy" (
  "id"         bigint   generated by default as identity (sequence NAME "public"."front_desk_records_id_seq") not null,
  "uid"        integer,
  "week_num"   smallint,
  "mon_min"    smallint,
  "tues_min"   smallint,
  "wed_min"    smallint,
  "thurs_min"  smallint,
  "fri_min"    smallint,
  "excuse_min" smallint,
  "excuse"     text,
  constraint "front_desk_records_pkey" primary key (id)
);

alter table "public"."front_desk_records_legacy"
  enable row level security;

create table "public"."study_session_records_legacy" (
  "id"         bigint   generated by default as identity (sequence NAME "public"."study_session_records_id_seq") not null,
  "uid"        integer,
  "week_num"   smallint,
  "mon_min"    smallint,
  "tues_min"   smallint,
  "wed_min"    smallint,
  "thurs_min"  smallint,
  "fri_min"    smallint,
  "excuse_min" smallint,
  "excuse"     text,
  constraint "study_session_records_pkey" primary key (id)
);

alter table "public"."study_session_records_legacy"
  enable row level security;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

create policy "authenticated_select_activity" on "public"."daily_scholar_activity"
  for select
  to "authenticated"
  using (((scholar_uid = (( select auth.uid() as uid))::text) or (exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.app_role = ANY (ARRAY['admin'::text, 'staff'::text, 'team_leader'::text, 'developer'::text])))))));

create policy "Enable read access for all users" on "public"."front_desk_records_legacy"
  for select
  to PUBLIC
  using (true);

create policy "developer_read_front_desk_records" on "public"."front_desk_records_legacy"
  for select
  to "authenticated"
  using (public.is_developer());

create policy "Enable read access for all users" on "public"."study_session_records_legacy"
  for select
  to PUBLIC
  using (true);

create policy "developer_read_study_session_records" on "public"."study_session_records_legacy"
  for select
  to "authenticated"
  using (public.is_developer());

create policy "whaf_select_policy" on "public"."whaf_form_logs"
  for all
  to "authenticated"
  using (((scholar_uid = (( select auth.uid() as uid))::text) or (exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.app_role = ANY (ARRAY['admin'::text, 'staff'::text, 'team_leader'::text, 'developer'::text])))))));

-- Supabase provisions this event trigger by default on every new project,
-- so a fresh project (confirmed while rebuilding staging on 2026-09-07)
-- already has it before this migration ever runs. `CREATE EVENT TRIGGER`
-- has no `IF NOT EXISTS`, so drop first for idempotency across both a fresh
-- project and production (where this migration created it originally).
drop event trigger if exists "ensure_rls";

create event trigger "ensure_rls"
  on ddl_command_end
  when tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  execute function "public"."rls_auto_enable"();

comment on extension "hypopg" is 'Hypothetical indexes for PostgreSQL';

comment on extension "index_advisor" is 'Query index advisor';

comment on extension "pg_cron" is 'Job scheduler for PostgreSQL';

comment on extension "pgjwt" is 'JSON Web Token API for Postgresql';

comment on table "public"."front_desk_records_legacy" is 'Frozen snapshot. Do not use. Minutes are computed on read from front_desk_logs; excuses live in scholar_week_excuses.';

comment on table "public"."study_session_records_legacy" is 'Frozen snapshot. Do not use. Minutes are computed on read from study_session_logs; excuses live in scholar_week_excuses.';

revoke all on table "public"."front_desk_records_legacy" from "anon";

grant references, select, trigger, truncate on table "public"."front_desk_records_legacy" to "anon";

revoke all on table "public"."front_desk_records_legacy" from "authenticated";

grant references, select, trigger, truncate on table "public"."front_desk_records_legacy" to "authenticated";

grant delete, insert, references, select, trigger, truncate, update on table "public"."front_desk_records_legacy" to "postgres", "service_role";

revoke all on table "public"."study_session_records_legacy" from "anon";

grant references, select, trigger, truncate on table "public"."study_session_records_legacy" to "anon";

revoke all on table "public"."study_session_records_legacy" from "authenticated";

grant references, select, trigger, truncate on table "public"."study_session_records_legacy" to "authenticated";

grant delete, insert, references, select, trigger, truncate, update on table "public"."study_session_records_legacy" to "postgres", "service_role";

select cron.schedule_in_database('nightly_resync_daily_scholar_activity', '0 2 * * *', 'SELECT public.full_resync_daily_scholar_activity();', 'postgres', null, true);
